FROM confluxchain/conflux-node:0.2.0
WORKDIR /root
COPY cfxrun run
RUN ln -s /root/run/conflux /usr/local/bin/conflux

WORKDIR /root/run
RUN chmod +x start.sh
RUN chmod +x conflux.sh
RUN chmod +x gene_account.sh

EXPOSE 12535 12536 12537 12538 12539 32323 32525
ENTRYPOINT [ "./start.sh" ]