version: '3'
services:

  node:
    build: .
    container_name: conflux_singlenode
    image: liqiazero/conflux-chain:${IMAGE_TAG:-latest}
    hostname: conflux-chain-singlenode
    ports:
     - "12357:12357"

