{
 "title": "Conflux Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Network", "query": "influxdb" },
   {
    "name": "nodeid",
    "label": "nodetag",
    "query": "show tag values from graph_statistic with key = \"node\""
   },
   { "name": "rpc_method", "label": "rpc_method", "query": "show field keys from rpc" }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "graph_statistic",
     "select": [
      [
       { "params": [ "best_epoch_number.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodeid$/" }
     ]
    }
   ]
  },
  {
   "title": "Metircs report time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metrics_report_time",
     "query": "SELECT mean(\"value\") FROM \"metrics_report_time\" WHERE (\"node\" =~ /^$nodeid$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(none)",
     "select": [
      [
       { "params": [ "best_epoch_number.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodeid$/" }
     ]
    }
   ]
  },
  {
   "title": "Invalid State Root Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_metrics",
     "query": "SELECT mean(\"invalid_blame_or_state_root_count.count\") FROM \"system_metrics\" WHERE (\"node\" =~ /^$nodeid$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(none)",
     "select": [
      [
       {
        "params": [
         "invalid_blame_or_state_root_count.count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodeid$/" }
     ]
    }
   ]
  },
  {
   "title": "Rpc Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"$rpc_method\") FROM \"rpc\" WHERE (\"node\" =~ /^$nodeid$/) AND $timeFilter GROUP BY time($__interval), \"node\" fill(none)"
    }
   ]
  }
 ]
}