FROM arm64v8/ubuntu
RUN apt-get update && apt-get install -y openssl libssl-dev
WORKDIR /root
# NOTE: conflux-binary/conflux should be runnable on arm64v8
COPY conflux-binary/run run   
RUN chmod +x /root/run/start.sh /root/run/conflux

WORKDIR /root/run
EXPOSE 12535 12536 12537 12538 12539 32323 32525
ENTRYPOINT [ "sh", "./start.sh" ]

