
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:d668a9f66b650bda9b49574d937adac55e19fc9b4979acf8c75cffe49a40a6b3
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./log/pos.log
  level: INFO
#storage:
  #dir: ./pos_db/db
