name: main network docker image build

on:
  push:
    tags:
      - "v*"
      - "!v*-mainnet"
      - "!v*-testnet"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove v prefix
        id: remove_prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{  github.ref_name }}
          file: ./Dockerfile.dev.buildx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: confluxchain/conflux-rust:${{ steps.remove_prefix.outputs.VERSION }},confluxchain/conflux-rust:latest
