name: main network docker image build

on:
  push:
    tags:
      - 'v*-mainnet'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args:
            - VERSION=${{ steps.branch_name.outputs.SOURCE_TAG }}
          file: ./Dockerfile.buildx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/conflux-rust:${{ steps.branch_name.outputs.SOURCE_TAG }}-mainnet