name: main network docker image build

on:
  push:
    tags:
      - "v*-mainnet"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove tag suffix
        id: remove_suffix
        env:
          TAG_NAME: ${{  github.ref_name }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          CLEANED_TAG_NAME=${TAG_NAME#v}
          CLEANED_TAG_NAME=${CLEANED_TAG_NAME%-mainnet}
          echo "CLEANED_TAG_NAME::${CLEANED_TAG_NAME}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ CLEANED_TAG_NAME }
          file: ./Dockerfile.buildx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: confluxchain/conflux-rust:${{ CLEANED_TAG_NAME }}-mainnet
